ShopOn/Models/ElectronicItem.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace ShopOn.Models
{
    public class ElectronicItem
    {
        public int ElectronicItemId { get; set; }
        public string Name { get; set; }
        public string BrandName { get; set; }
        public string Specifications { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl1 { get; set; }
        public string ImageUrl2 { get; set; }
        public string ImageUrl3 { get; set; }
        public bool DealOfTheDay { get; set; }
        public bool InStock { get; set; }
        public int CategoryId { get; set; }
         [BindNever]
         [ValidateNever]
         public Category Category { get; set; }
    }
}

ShopOn/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ShopOn.Models;

namespace ShopOn.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IConfiguration _configuration;
        string BaseAddress2;
        public CategoryController(IConfiguration configuration)
        {
            _configuration = configuration;
            this.BaseAddress2 = _configuration.GetValue<string>("BaseAddress2");
        }

        public IActionResult GetAllCategoriesItems()
        {
            var URL = this.BaseAddress2 + "GetAllCategories";
            var AllCategoryItems = APIShopOnURL.GetApiCategoryData(URL);
            return View(AllCategoryItems.Result);
        }

    }
}

ShopOn/Controllers/ElectronicItemController.cs
using Microsoft.AspNetCore.Mvc;
using ShopOn.Models;

namespace ShopOn.Controllers
{
    public class ElectronicItemController : Controller
    {
        private readonly IConfiguration _configuration;
        string BaseAddress1;
        public ElectronicItemController(IConfiguration configuration)
        {
            _configuration = configuration;
            this.BaseAddress1 = _configuration.GetValue<string>("BaseAddress1");
        }
        public IActionResult SearchList(string searchValue)
        {
            var URL = this.BaseAddress1 + "GetAllItems";
            var electronicItems = APIShopOnURL.GetApiElectronicItemsData(URL);
            var ResultOfsearch = electronicItems.Result.Where(x => x.Name.ToLower().Contains(searchValue.ToLower()) || x.BrandName.ToLower().Contains(searchValue.ToLower()));
            return View(ResultOfsearch);
        }
        public IActionResult SortList(int Id)
        {
            var URL = this.BaseAddress1 + "GetAllItems";
            var AllItems = APIShopOnURL.GetApiElectronicItemsData(URL);

            if (Id == 1)
            {
                return View(AllItems.Result.OrderBy(x =>x.Price));
            }
            else
            {
                return View(AllItems.Result.OrderByDescending(x=>x.Price));
            }
        }

        public IActionResult GetAllItems(int CategoryId)
        {
            var URL = this.BaseAddress1 + "GetAllItems";
            var AllItems = APIShopOnURL.GetApiElectronicItemsData(URL);

            if (CategoryId > 0)
            {
                return View(AllItems.Result.Where(x => x.CategoryId == CategoryId));
            }
            else
            {
                return View(AllItems.Result);
            }
        }

        public async Task<IActionResult> AddToWishList(int id)
        {
            var URL = this.BaseAddress1 + "AddToWishList?ItemIdNumber=" + id;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.PostAsJsonAsync(URL, id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetAllItems");

        }

        public IActionResult GetWishListItems()
        {
            List<ElectronicItem> electronicItems = new List<ElectronicItem>();
            var URL = this.BaseAddress1 + "GetWishListDetails";
            var Ids = APIShopOnURL.GetApiWishListData(URL);
            var AllDistinctIds = Ids.Result.DistinctBy(x => x.ItemIdentityNumber);
            var AllElectronicItems = APIShopOnURL.GetApiElectronicItemsData(this.BaseAddress1 + "GetAllItems");
            foreach (var item in AllDistinctIds)
            {
                var AllItems = AllElectronicItems.Result.FirstOrDefault(x => x.ElectronicItemId == item.ItemIdentityNumber);
                if (AllItems != null)
                {
                    electronicItems.Add(AllItems);
                }
            }
            return View(electronicItems);
        }


        public async Task<IActionResult> DeleteWishListItem(int ElectronicItemId)
        {
            var URL = BaseAddress1 + "RemoveWishListItem?id=" + ElectronicItemId;
            // var student = studentRepository.GetAllStudents().FirstOrDefault(student => student.StudentID == studentId);
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync(URL))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetWishListItems");
        }

        public IActionResult Details(int id)
        {
            var URL = this.BaseAddress1 + "GetAllItems";
            var electronicItems = APIShopOnURL.GetApiElectronicItemsData(URL);
            var AllItems = electronicItems.Result.FirstOrDefault(x => x.ElectronicItemId == id);
            return View(AllItems);
        }

        public IActionResult Edit(int id)
        {
            var URL = this.BaseAddress1 + "GetAllItems";
            var electronicItems = APIShopOnURL.GetApiElectronicItemsData(URL);
            var AllItems = electronicItems.Result.FirstOrDefault(x => x.ElectronicItemId == id);
            return View(AllItems);
        }

        public async Task<IActionResult> UpdateElectronicItem(ElectronicItem electronicItem)
        {
            var URL = this.BaseAddress1 + "UpdateElectronicItem";
           
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.PutAsJsonAsync(URL, electronicItem))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetAllItems");
        }


        public IActionResult Create()
        {
            return View();
        }
        public async Task<IActionResult> CreateElectronicItem(ElectronicItem item)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.PostAsJsonAsync(BaseAddress1 + "AddElectronicItem", item))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetAllItems");
        }


        public async Task<IActionResult> DeleteElectronicItem(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync(BaseAddress1 + "DeleteElectroicItem?Id=" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetAllItems");
        }


    }
}

ShopOn/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShopOn.Models;

namespace ShopOn.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IConfiguration _configuration;
        string BaseAddress1;
        public ShoppingCartController(IConfiguration configuration)
        {
            _configuration = configuration;
            this.BaseAddress1 = _configuration.GetValue<string>("BaseAddress1");
        }

        public IActionResult BuyNow(int ElectronicItemId)
        {
            var URL = this.BaseAddress1 + "GetAllPies";
            var electronicItems = APIShopOnURL.GetApiElectronicItemsData(URL);
            return View(electronicItems.Result.FirstOrDefault(x => x.ElectronicItemId == ElectronicItemId));
        }



        public async Task<IActionResult> AddToCart(int ElectronicItemId)
        {

            var URL = this.BaseAddress1 + "AddToCartItem?itemId=" + ElectronicItemId;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.PostAsJsonAsync(URL, ElectronicItemId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetAllItems", "ElectronicItem");

        }

        public async Task<IActionResult> AddToCart11(int ElectronicItemId)
        {

            var URL = this.BaseAddress1 + "AddToCartItem?itemId=" + ElectronicItemId;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.PostAsJsonAsync(URL, ElectronicItemId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetCartItems");

        }



        public async Task<IActionResult> GetCartItems()
        {
            var URL = this.BaseAddress1 + "GetCartItems";
            var CartDetails = APIShopOnURL.GetApiCartData(URL);
            ViewBag.OrderTotal = CartDetails.Result.Sum(x => (x.ItemPrice * x.Quantity));
            return View(CartDetails.Result);
        }




        public async Task<IActionResult> RemoveCartItem(int CartId)
        {
            var URL = this.BaseAddress1 + "RemoveCartItem?id=" + CartId;
            var status = APIShopOnURL.RemoveData(URL);
            return RedirectToAction("GetCartItems");
        }



        public async Task<IActionResult> DecreamentCartItem(int ElectronicItemId)
        {
            var URL = this.BaseAddress1 + "DecreamentCartItem?itemId=" + ElectronicItemId;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync(URL))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetCartItems");
        }

    }
}

ShopOn/Views/ElectronicItem/Create.cshtml
@model ShopOn.Models.ElectronicItem

@{
    ViewData["Title"] = "CreateElectronicItem";
}

<h1>CreateElectronicItem</h1>

<h4>ElectronicItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateElectronicItem" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandName" class="control-label"></label>
                <input asp-for="BrandName" class="form-control" />
                <span asp-validation-for="BrandName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specifications" class="control-label"></label>
                <input asp-for="Specifications" class="form-control" />
                <span asp-validation-for="Specifications" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongDescription" class="control-label"></label>
                <input asp-for="LongDescription" class="form-control" />
                <span asp-validation-for="LongDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl1" class="control-label"></label>
                <input asp-for="ImageUrl1" class="form-control" />
                <span asp-validation-for="ImageUrl1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl2" class="control-label"></label>
                <input asp-for="ImageUrl2" class="form-control" />
                <span asp-validation-for="ImageUrl2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl3" class="control-label"></label>
                <input asp-for="ImageUrl3" class="form-control" />
                <span asp-validation-for="ImageUrl3" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="DealOfTheDay" /> @Html.DisplayNameFor(model => model.DealOfTheDay)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="InStock" /> @Html.DisplayNameFor(model => model.InStock)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShopOn/Views/ElectronicItem/Details.cshtml
@model ShopOn.Models.ElectronicItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>




<div class="thumbnail">
    <div align="center"><img alt="Image of pie" src="@Model.ImageUrl1" style="width:30%"></div>
     <div align="center"><img alt="Image of pie" src="@Model.ImageUrl2" style="width:30%"></div>
      <div align="center"><img alt="Image of pie" src="@Model.ImageUrl3" style="width:30%"></div>
    <div class="caption-full">
        <h3 class="pull-right" align="center">&#36; @Model.Price</h3>
        <h3 align="center">
            <a href="#" style="text-decoration:none">@Model.Name</a>
        </h3>
        <h3 align="center">
            <a href="#" style="text-decoration:none">@Model.BrandName</a>
        </h3>
        <h4>@Model.ShortDescription</h4>
        <p align="justify"><h5 style="color:darkred">@Model.LongDescription</h5></p>
       
        
 
        <div class="addToCart">
         
                 @{ 
                     if(@Model.InStock){
                            <p class="button">
                    <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="BuyNow"
                   asp-route-ElectronicItemId="@Model.ElectronicItemId">BUY NOW</a>
                </p>

                 <p class="button">
                    <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToCart"
                   asp-route-ElectronicItemId="@Model.ElectronicItemId">ADD TO CART</a></p>
                }
                else
                {
                    <h4 style="color:red">OUT OF STOCK</h4>
                }
            }

                        <p class="button">
                     

                    <a class="btn btn-danger" asp-controller="ElectronicItem" asp-action="DeleteElectronicItem" asp-route-id="@Model.ElectronicItemId">DELETE</a>
              
                </p>
            </div>
        </div>
    </div>

    <div>
        <a  class="btn btn-info" asp-action="Edit" asp-route-id="@Model?.ElectronicItemId">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>

ShopOn/Views/ElectronicItem/Edit.cshtml
@model ShopOn.Models.ElectronicItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ElectronicItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateElectronicItem" method="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ElectronicItemId" class="control-label"></label>
                <input asp-for="ElectronicItemId" class="form-control" />
                <span asp-validation-for="ElectronicItemId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandName" class="control-label"></label>
                <input asp-for="BrandName" class="form-control" />
                <span asp-validation-for="BrandName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specifications" class="control-label"></label>
                <input asp-for="Specifications" class="form-control" />
                <span asp-validation-for="Specifications" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongDescription" class="control-label"></label>
                <input asp-for="LongDescription" class="form-control" />
                <span asp-validation-for="LongDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl1" class="control-label"></label>
                <input asp-for="ImageUrl1" class="form-control" />
                <span asp-validation-for="ImageUrl1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl2" class="control-label"></label>
                <input asp-for="ImageUrl2" class="form-control" />
                <span asp-validation-for="ImageUrl2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl3" class="control-label"></label>
                <input asp-for="ImageUrl3" class="form-control" />
                <span asp-validation-for="ImageUrl3" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="DealOfTheDay" /> @Html.DisplayNameFor(model => model.DealOfTheDay)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="InStock" /> @Html.DisplayNameFor(model => model.InStock)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShopOn/Views/ElectronicItem/GetAllItems.cshtml
@using ShopOn.Models
@model IEnumerable<ElectronicItem>


@* <marquee><a asp-controller="Category" asp-action="List1" style="text-decoration:none" id="demo" onmouseenter="mouseEnter()" onmouseleave="mouseLeave()">&#9888; &#x26A0; Delicios, Smooth, Hot, Spicy, Chocolate Pies Are Ready With 60% Discount!!</a></marquee>*@

 <div class="container">
@foreach (var electronicItem in Model)
    {
        
          
                <div class="gallery">
                    <a asp-controller="ElectronicItem" asp-action="Details" asp-route-id="@electronicItem.ElectronicItemId"> <img src="@electronicItem.ImageUrl1" alt=""> </a>
                    <div class="desc">
                        <h3 class="pull-right">@electronicItem.Price.ToString("c")</h3>  
                        <a asp-controller="Pie" asp-action="Details" asp-route-id="@electronicItem.ElectronicItemId" style="text-decoration:none">   <h2 style="color:black">@electronicItem.BrandName</h2> </a>
                      
                          
                      &nbsp; 
                
                        <a class="btn btn-warning" asp-controller="ShoppingCart" asp-action="BuyNow" asp-route-ElectronicItemId="@electronicItem.ElectronicItemId"> BUY NOW </a>   &nbsp;&nbsp; &nbsp;

                        <a class="btn btn-warning" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-ElectronicItemId="@electronicItem.ElectronicItemId"> ADD TO CART </a>
                        &nbsp; <a asp-controller="ElectronicItem" asp-action="AddToWishList" asp-route-id="@electronicItem.ElectronicItemId" class="temp" >&#10084;</a>
                        &nbsp;&nbsp; 

                    </div>
                </div>
            
        
    }
</div>
  
<style>
    .container{
        max-width:1400px;
        margin:25px;
        background: white;
        overflow:auto;
    }
    .gallery{
        margin:2px;
        border:5px solid #D3D3D3 ;
       float:left;
        width:390px;
    }
    .gallery img{
        width:100%;
        height:250px;
    }
    .desc{
        padding:5px;
        text-align:center;
    }

    .temp:link, .temp:visited {
  background-color: white;
  color: Red;
  padding: 15px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}

.temp:hover, .temp:active {
  background-color:yellow;
}

</style>

ShopOn/Views/ElectronicItem/GetWishListItems.cshtml
@model IEnumerable<ElectronicItem>

   <h4 style="text-align:center">WISHLIST </h4>

@{
    if(Model.Count()==0)
    {
    <h4 style="align-content:center"> :( Oops No Items in WishList !! </h4>
    }
}
 <div class="container">
@foreach (var electronicItem in Model)
{
    
        <div class="gallery">
          <a asp-controller="ElectronicItem" asp-action="Details" asp-route-id="@electronicItem.ElectronicItemId"> <img src="@electronicItem.ImageUrl1" alt="ImageLogos"> </a>
            <div class="desc">
                <h3 class="pull-right">@electronicItem.Price.ToString("c")</h3>   
             <a asp-controller="ElectronicItem" asp-action="Details" asp-route-id="@electronicItem.ElectronicItemId" style="text-decoration:none">   <h2>@electronicItem.BrandName</h2> </a>
               
                 @{ if(@electronicItem.InStock){
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="BuyNow" asp-route-ElectronicItemId="@electronicItem.ElectronicItemId"> BUY NOW </a>
               
                        <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-ElectronicItemId="@electronicItem.ElectronicItemId"> ADD TO CART </a>
                    }
                    else
                    {
                        <h5 style="color:red">OUT OF STOCK</h5>
                    }
                }

@*
             <div class="addToCart">
                <p class="button">
                    <a class="btn btn-primary" 
                       asp-controller="ShoppingCarttt" 
                       asp-action="AddToShoppingCart"
                       asp-route-pieId="@pie.PieId">Add to cart</a>
                </p>
            </div>*@


             
               
            </div>
             <a class="btn btn-outline-danger" asp-controller="ElectronicItem" asp-action="DeleteWishListItem" asp-route-ElectronicItemId="@electronicItem.ElectronicItemId" class="temp" >Remove</a>
        </div>
        
               
    
   
}
</div>
  
<style>
    .container{
        max-width:1400px;
        margin:25px;
        background: white;
        overflow:auto;
    }
    .gallery{
        margin:2px;
        border:5px solid #D3D3D3 ;
       float:left;
        width:390px;
    }
    .gallery img{
        width:100%;
        height:250px;
    }
    .desc{
        padding:5px;
        text-align:center;
    }

    .temp:link, .temp:visited {
  background-color: white;
  color: Red;
  padding: 15px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}

.temp:hover, .temp:active {
  background-color:yellow;
}

</style>

ShopOn/Views/ElectronicItem/SearchList.cshtml
@using ShopOn.Models
@model IEnumerable<ElectronicItem>


@* <marquee><a asp-controller="Category" asp-action="List1" style="text-decoration:none" id="demo" onmouseenter="mouseEnter()" onmouseleave="mouseLeave()">&#9888; &#x26A0; Delicios, Smooth, Hot, Spicy, Chocolate Pies Are Ready With 60% Discount!!</a></marquee>*@

 <div class="container">
@foreach (var electronicItem in Model)
    {
        
          
                <div class="gallery">
                    <a asp-controller="ElectronicItem" asp-action="Details" asp-route-id="@electronicItem.ElectronicItemId"> <img src="@electronicItem.ImageUrl1" alt=""> </a>
                    <div class="desc">
                        <h3 class="pull-right">@electronicItem.Price.ToString("c")</h3>  
                        <a asp-controller="Pie" asp-action="Details" asp-route-id="@electronicItem.ElectronicItemId" style="text-decoration:none">   <h2 style="color:black">@electronicItem.BrandName</h2> </a>
                      
                          
                      &nbsp; 
                
                        <a class="btn btn-warning" asp-controller="ShoppingCart" asp-action="BuyNow" asp-route-ElectronicItemId="@electronicItem.ElectronicItemId"> BUY NOW </a>   &nbsp;&nbsp; &nbsp;

                        <a class="btn btn-warning" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-ElectronicItemId="@electronicItem.ElectronicItemId"> ADD TO CART </a>
                        &nbsp; <a asp-controller="ElectronicItem" asp-action="AddToWishList" asp-route-id="@electronicItem.ElectronicItemId" class="temp" >&#10084;</a>
                        &nbsp;&nbsp; 

                    </div>
                </div>
            
        
    }
</div>
  
<style>
    .container{
        max-width:1400px;
        margin:25px;
        background: white;
        overflow:auto;
    }
    .gallery{
        margin:2px;
        border:5px solid #D3D3D3 ;
       float:left;
        width:390px;
    }
    .gallery img{
        width:100%;
        height:250px;
    }
    .desc{
        padding:5px;
        text-align:center;
    }

    .temp:link, .temp:visited {
  background-color: white;
  color: Red;
  padding: 15px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}

.temp:hover, .temp:active {
  background-color:yellow;
}

</style>

ShopOn/Views/ElectronicItem/SortList.cshtml
@using ShopOn.Models
@model IEnumerable<ElectronicItem>


@* <marquee><a asp-controller="Category" asp-action="List1" style="text-decoration:none" id="demo" onmouseenter="mouseEnter()" onmouseleave="mouseLeave()">&#9888; &#x26A0; Delicios, Smooth, Hot, Spicy, Chocolate Pies Are Ready With 60% Discount!!</a></marquee>*@

 <div class="container">
@foreach (var electronicItem in Model)
    {
        
          
                <div class="gallery">
                    <a asp-controller="ElectronicItem" asp-action="Details" asp-route-id="@electronicItem.ElectronicItemId"> <img src="@electronicItem.ImageUrl1" alt=""> </a>
                    <div class="desc">
                        <h3 class="pull-right">@electronicItem.Price.ToString("c")</h3>  
                        <a asp-controller="Pie" asp-action="Details" asp-route-id="@electronicItem.ElectronicItemId" style="text-decoration:none">   <h2 style="color:black">@electronicItem.BrandName</h2> </a>
                      
                          
                      &nbsp; 
                
                        <a class="btn btn-warning" asp-controller="ShoppingCart" asp-action="BuyNow" asp-route-ElectronicItemId="@electronicItem.ElectronicItemId"> BUY NOW </a>   &nbsp;&nbsp; &nbsp;

                        <a class="btn btn-warning" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-ElectronicItemId="@electronicItem.ElectronicItemId"> ADD TO CART </a>
                        &nbsp; <a asp-controller="ElectronicItem" asp-action="AddToWishList" asp-route-id="@electronicItem.ElectronicItemId" class="temp" >&#10084;</a>
                        &nbsp;&nbsp; 

                    </div>
                </div>
            
        
    }
</div>
  
<style>
    .container{
        max-width:1400px;
        margin:25px;
        background: white;
        overflow:auto;
    }
    .gallery{
        margin:2px;
        border:5px solid #D3D3D3 ;
       float:left;
        width:390px;
    }
    .gallery img{
        width:100%;
        height:250px;
    }
    .desc{
        padding:5px;
        text-align:center;
    }

    .temp:link, .temp:visited {
  background-color: white;
  color: Red;
  padding: 15px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}

.temp:hover, .temp:active {
  background-color:yellow;
}

</style>